# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_user_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.all_user_table = QtWidgets.QTableWidget(self.centralwidget)
        self.all_user_table.setObjectName("all_user_table")
        self.all_user_table.setColumnCount(0)
        self.all_user_table.setRowCount(0)
        self.gridLayout.addWidget(self.all_user_table, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"height:100px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setStyleSheet("border:none")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/uname.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.user_select = QtWidgets.QLineEdit(self.frame)
        self.user_select.setStyleSheet("border-radius:10px;\n"
"height:30px;\n"
"border:2px solid black;")
        self.user_select.setObjectName("user_select")
        self.horizontalLayout.addWidget(self.user_select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("border:none\n"
"")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/record1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.id_select = QtWidgets.QLineEdit(self.frame)
        self.id_select.setStyleSheet("border-radius:10px;\n"
"height:30px;\n"
"border:2px solid black;")
        self.id_select.setObjectName("id_select")
        self.horizontalLayout.addWidget(self.id_select)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.select_btn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_btn.setFont(font)
        self.select_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(25, 197, 254);\n"
"    font: 16pt \"Arial\";\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    width:150px;\n"
"    height:40px;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background:#FFDC35;\n"
"    border:1px solid blue;\n"
" }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_btn.setIcon(icon2)
        self.select_btn.setIconSize(QtCore.QSize(30, 30))
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout.addWidget(self.select_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 20)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.input_pic = QtWidgets.QPushButton(self.frame_2)
        self.input_pic.setStyleSheet("QPushButton{\n"
"    background-color: rgb(25, 197, 254);\n"
"    font: 16pt \"Arial\";\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    width:150px;\n"
"    height:40px;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background:#FFDC35;\n"
"    border:1px solid blue;\n"
" }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_pic.setIcon(icon3)
        self.input_pic.setIconSize(QtCore.QSize(30, 30))
        self.input_pic.setObjectName("input_pic")
        self.horizontalLayout_2.addWidget(self.input_pic)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.input_excel = QtWidgets.QPushButton(self.frame_2)
        self.input_excel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(25, 197, 254);\n"
"    font: 16pt \"Arial\";\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    width:150px;\n"
"    height:40px;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background:#FFDC35;\n"
"    border:1px solid blue;\n"
" }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_excel.setIcon(icon4)
        self.input_excel.setIconSize(QtCore.QSize(30, 30))
        self.input_excel.setObjectName("input_excel")
        self.horizontalLayout_2.addWidget(self.input_excel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.add_btn = QtWidgets.QPushButton(self.frame_2)
        self.add_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(25, 197, 254);\n"
"    font: 16pt \"Arial\";\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    width:150px;\n"
"    height:40px;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background:#FFDC35;\n"
"    border:1px solid blue;\n"
" }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon5)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.del_btn = QtWidgets.QPushButton(self.frame_2)
        self.del_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(25, 197, 254);\n"
"    font: 16pt \"Arial\";\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    width:150px;\n"
"    height:40px;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background:#FFDC35;\n"
"    border:1px solid blue;\n"
" }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../img/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon6)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pic_input = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/花花/.designer/backup/img/pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic_input.setIcon(icon7)
        self.pic_input.setObjectName("pic_input")
        self.excel_input = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/花花/.designer/backup/img/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excel_input.setIcon(icon8)
        self.excel_input.setObjectName("excel_input")
        self.select_all = QtWidgets.QAction(MainWindow)
        self.select_all.setObjectName("select_all")
        self.select_today = QtWidgets.QAction(MainWindow)
        self.select_today.setObjectName("select_today")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人员信息"))
        self.select_btn.setText(_translate("MainWindow", " 搜 索"))
        self.input_pic.setText(_translate("MainWindow", " 导入图片"))
        self.input_excel.setText(_translate("MainWindow", " 导入表格"))
        self.add_btn.setText(_translate("MainWindow", "新增"))
        self.del_btn.setText(_translate("MainWindow", "删除"))
        self.pic_input.setText(_translate("MainWindow", "图片批量导入"))
        self.excel_input.setText(_translate("MainWindow", "表格批量导入"))
        self.select_all.setText(_translate("MainWindow", "显示所有人员信息"))
        self.select_today.setText(_translate("MainWindow", "查询当日通行记录"))
