# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        self.mainWindow = QtWidgets.QWidget(MainWindow)
        self.mainWindow.setObjectName("mainWindow")
        self.logo_name = QtWidgets.QLabel(self.mainWindow)
        self.logo_name.setGeometry(QtCore.QRect(310, 30, 171, 61))
        self.logo_name.setStyleSheet("font: 30pt \"Bauhaus 93\";")
        self.logo_name.setObjectName("logo_name")
        self.register_username = QtWidgets.QLineEdit(self.mainWindow)
        self.register_username.setGeometry(QtCore.QRect(330, 110, 201, 31))
        self.register_username.setStyleSheet("QLineEdit{\n"
"    border-radius:5px;\n"
"    border:1px black solid;\n"
"}\n"
"QLineEdit:hover{\n"
"    background:yellow;\n"
"    padding:2px;\n"
"\n"
"}")
        self.register_username.setObjectName("register_username")
        self.register_password = QtWidgets.QLineEdit(self.mainWindow)
        self.register_password.setGeometry(QtCore.QRect(330, 160, 201, 31))
        self.register_password.setStyleSheet("QLineEdit{\n"
"    border-radius:5px;\n"
"    border:1px black solid;\n"
"}\n"
"QLineEdit:hover{\n"
"    background:yellow;\n"
"    padding:2px;\n"
"\n"
"}")
        self.register_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_password.setObjectName("register_password")
        self.register_btn = QtWidgets.QPushButton(self.mainWindow)
        self.register_btn.setGeometry(QtCore.QRect(260, 260, 271, 41))
        self.register_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 11pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:yellow;\n"
"    color:black;\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.close_btn = QtWidgets.QPushButton(self.mainWindow)
        self.close_btn.setGeometry(QtCore.QRect(750, 20, 30, 30))
        self.close_btn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.close_btn.setObjectName("close_btn")
        self.again_password = QtWidgets.QLineEdit(self.mainWindow)
        self.again_password.setGeometry(QtCore.QRect(330, 210, 201, 31))
        self.again_password.setStyleSheet("QLineEdit{\n"
"    border-radius:5px;\n"
"    border:1px black solid;\n"
"}\n"
"QLineEdit:hover{\n"
"    background:yellow;\n"
"    padding:2px;\n"
"\n"
"}")
        self.again_password.setText("")
        self.again_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.again_password.setObjectName("again_password")
        self.logo1 = QtWidgets.QPushButton(self.mainWindow)
        self.logo1.setGeometry(QtCore.QRect(250, 110, 41, 31))
        self.logo1.setStyleSheet("width:30px;\n"
"height:30px;\n"
"border:none;")
        self.logo1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/reg_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo1.setIcon(icon)
        self.logo1.setIconSize(QtCore.QSize(30, 30))
        self.logo1.setObjectName("logo1")
        self.logo2 = QtWidgets.QPushButton(self.mainWindow)
        self.logo2.setGeometry(QtCore.QRect(250, 160, 41, 28))
        self.logo2.setStyleSheet("width:30px;\n"
"height:30px;\n"
"border:none;")
        self.logo2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/reg_psd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo2.setIcon(icon1)
        self.logo2.setIconSize(QtCore.QSize(30, 30))
        self.logo2.setObjectName("logo2")
        self.logo3 = QtWidgets.QPushButton(self.mainWindow)
        self.logo3.setGeometry(QtCore.QRect(250, 210, 41, 31))
        self.logo3.setStyleSheet("width:30px;\n"
"height:30px;\n"
"border:none;")
        self.logo3.setText("")
        self.logo3.setIcon(icon1)
        self.logo3.setIconSize(QtCore.QSize(30, 30))
        self.logo3.setObjectName("logo3")
        MainWindow.setCentralWidget(self.mainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AiFace"))
        self.logo_name.setText(_translate("MainWindow", "AiFace"))
        self.register_username.setPlaceholderText(_translate("MainWindow", "用户名"))
        self.register_password.setPlaceholderText(_translate("MainWindow", "密码"))
        self.register_btn.setText(_translate("MainWindow", "注册"))
        self.close_btn.setText(_translate("MainWindow", "×"))
        self.again_password.setPlaceholderText(_translate("MainWindow", "确认密码"))
